$(document).ready(function(){
	$('button[type=submit]').click(function(){
		jQuery.ajax({
			data:{
				id:$('input[name=id]').val
			},
			url:'do',
			success:function(data){
				$('#mm').text(data);
			}
		});
		$('#mm').html('loading');
	});
});